question_data = [
        {"category": "Geography",
         "type": "boolean",
         "difficulty": "medium",
         "question": "Seoul is the capital of North Korea.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Peyton Manning retired after winning Super Bowl XLIX.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean",
         "difficulty": "easy",
         "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean",
         "difficulty": "easy",
         "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "Adolf Hitler was tried at the Nuremberg trials.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "New Haven is the capital city of the state of Connecticut in the United States.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean",
         "difficulty": "easy",
         "question": "&quot;Green Eggs and Ham&quot; consists of only 50 different words.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean",
         "difficulty": "hard",
         "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
         "difficulty": "medium",
         "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean",
         "difficulty": "medium",
         "question": "The most frequent subconscious activity repeated by the human body is blinking.",
         "correct_answer": "False", "incorrect_answers": ["True"]}]

